# Generated by Django 4.0.3 on 2022-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipe',
            name='recipe_image',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='recipe_time_to_cook',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
