# Generated by Django 4.0.3 on 2022-12-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favoriterecipe_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='recipe_time_to_cook',
            field=models.CharField(max_length=250),
        ),
    ]
